### ISSUE TITLE
Convert返回Infinity

### ISSUE THREAD

**Issue by RickyHuo** [childe/hangout#110]
```
- Convert:
    from:
        to: double
        setto_if_fail: 0
```

当from为723E095012时， 返回Infinity， 并没有抛异常
