### ISSUE TITLE
routing中变量取值取不出来

### ISSUE THREAD

**Issue by mrzhangxing** [childe/hangout#112]
首先感谢作者的大力支持哈，前阵子提了这个需求，后来耽搁了没上线；
我是想用字段中一个值做routing

```
filters:
    - Add:
       fields:
          route_diy: 'abc'

outputs:
    - Elasticsearch:
        cluster: es-nginx
        hosts:
            - "192.168.1.22:9300"
        index: 'test-%{route_diy}'
        index_type: test # default logs
        bulk_actions: 20000 # default 20000
        bulk_size: 15   #default 15
        flush_interval: 10  #default 10
        concurrent_requests: 0  #default 0
        sniff: false #default true
        timezone: "Asia/Shanghai"
        route: '%{route_diy}'
```
以上是部分测试配置，自定义的route_diy在index可以取到，生成的index就是test_abc,但是routing取不到，ES中查看routing：   "_routing": "%{route_diy}"，我记得刚开始测试没问题，不知道现在哪里出错了
