### ISSUE TITLE
UnknownFormatConversionException

### ISSUE THREAD

**Issue by timchenxiaoyu** [childe/hangout#120]
```
inputs:
    - NewKafka:
        topic:
            k8s-log: 1
        codec: json
        consumer_settings:
            bootstrap.servers: 10.39.15.13:9092
            value.deserializer: org.apache.kafka.common.serialization.StringDeserializer
            key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
            group.id: logstash
outputs:
    - Elasticsearch:
        cluster: hangoutcluster
        hosts:
          - 10.39.15.2
        index: 'hangout-%{user}-%{+YYYY.MM.dd}'
        codec: json
        index_type: logs # default logs
        bulk_actions: 20000 #default 20000
        bulk_size: 15 # default 15 MB
        flush_interval: 10 # default 10 seconds
        concurrent_requests: 0 # default 0, concurrent_requests设置成大于0的数, 意思着多线程处理, 以我应用的经验,还有是一定OOM风险的,强烈建议设置为0
        timezone: "Asia/Shanghai" # defaut UTC 时区. 只用于生成索引名字的字符串格式化
        sniff: false #default true
```

 ERROR com.ctrip.ops.sysdev.baseplugin.BaseInput - java.util.UnknownFormatConversionException: Conversion = '{'
