### ISSUE TITLE
ElasticsearchHTTP可以支持https吗？

### ISSUE THREAD

**Issue by mrzhangxing** [childe/hangout#122]
```
outputs:
    - ElasticsearchHTTP:
         cluster: ops-test 
         hosts:
           - 10.13.0.10
         index: 'ops'
         user: admin
         password: admin 
         index_type: "nginx_log" # default logs
         bulk_actions: 5 #default 20000
         sniff: true #default true

    #- Stdout:
    #    {}
```
以上是我的配置，kafka消费至ES6.2.2，有两个问题想咨询下：
1、目前hangout支持https吗？
2、以上的配置，好像stdout并没有关掉，我已经注释掉Stdout，但是运行后就一直疯狂输出信息，作者有遇到这个问题吗？
