### ISSUE TITLE
可否通过Hangout将kafka的数据分散写入不同的index

### ISSUE THREAD

**Issue by mrzhangxing** [childe/hangout#124]
又来麻烦作者了哈，我请问下目前的hangout功能能否将一份kafka数据，拆分到多个索引当中，目前是源数据太大，不好拆分，写入一个索引，ES性能有些影响。

比如kafka存了10w条数据，我想写入2个索引中，每个索引至放5w这样的数据量，我目前利用add参数，增加了一个字段，使用字段中的英文首字母，拆分了26索引，但是这样太多了，（另外还多了一个无用字段）

我想的想法是，对时间戳(秒)取模的方式，然后定义为索引名字变量：

```
#"@timestamp":"2018-05-22T15:42:07+08:00"

    #先得到"2018-05-22T15:42:07"
    - Add:
       fields:
          index_tmp: '<#assign a=@timestamp?split("+")>${a[0]}'
    #在得到"07",然后取模2
    - Add:
       fields:
          index: '<#assign a=index_tmp?split(":")>${(a[2])?number % 2}'

     #然后在删除tmp字段
     - Remove:
        fields:
            - index_tmp

```
如上写法有两个问题：
1、freemarker可否在一行多次逻辑处理，:"2018-05-22T15:42:07+08:00"，一次性得到07这个值
2、取出来后，可否直接当做变量使用，而不是使用ADD字段

不是很熟悉freemarker的语法，求助下作者。
