### ISSUE TITLE
ES节点某一台出现故障时候，hangout就停止消费

### ISSUE THREAD

**Issue by mrzhangxing** [childe/hangout#126]
最近我这边的ES集群不太稳定，可能是不是伴随着1-2台的节点宕机，某个节点宕机并不影响集群状态，但每次宕机后，hangout就不在消费，kafka一直堆积，重启下hangout才能恢复。

hangout配置如下
```
inputs:
    - Kafka:
        codec: json
        topic: 
          hdp_teu_ops_nginx_log: 18 
        consumer_settings:
          group.id: hdp_teu_ops_nginx_log-hangout-es6-hdd
          zookeeper.connect: "10.100.81.215:2181/kafka_cluster"
          auto.commit.interval.ms: "20000"
          socket.receive.buffer.bytes: "1048576"
          fetch.message.max.bytes: "1048576"
          num.consumer.fetchers: "1"
filters:
    - Filters:
        if:
            - '<#if message??>true</#if>' 
        filters:
            - Grok:
                match:
                  - '(?<msg>{"@timestamp":.*"request_uri":([^\?]+)\?)'
                  - '(?<msg>{"@timestamp":.*"request_uri":(\S{1,60}))'
            - Gsub:
                fields:
                    msg: ['$','"}']
            - Json:
                field: msg
                remove_fields: ['message']
    - GeoIP2:
        source: client_ip
        database: '/opt/soft/hangout_es6/etc/other/GeoLite2-City.mmdb'

    - Remove:
        fields:
            - msg
    - Add:
       fields:
          request_url: '<#assign a=request_uri?split("?")>${a[0]}'
       if:
         - '<#if request_uri??>true</#if>'

outputs:
    - Elasticsearch:
        cluster: ops-es-nginx-hdd
        hosts: 
            - 10.1.6.2
            - 10.1.3.21
            - 10.1.0.66 
        index: 'hangout-hdp_teu_ops_nginx_log-%{+YYYY.MM.dd}'
        index_type: nginx_log # default logs
        bulk_actions: 20000 # default 20000
        bulk_size: 15   #default 15
        flush_interval: 10  #default 10
        concurrent_requests: 0  #default 0
        sniff: true  #default true
        timezone: "Asia/Shanghai"
```
