### ISSUE TITLE
newkafka 怎么在output elasticsearch 用kafka 做index 

### ISSUE THREAD

**Issue by mylinuxsa** [childe/hangout#132]
读取多个topic，想用topic 做微index 名称写入es中？

**Comment by ooooldman** [comment]
- NewKafka:
    topic:
        nginx: 1
        tomcat: 1
    codec: json
    consumer_settings:
        bootstrap.servers: 192.168.0.1:9092
        value.deserializer: org.apache.kafka.common.serialization.StringDeserializer
        key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
        group.id: hangout
- Elasticsearch:
cluster: prod
hosts:
  - 192.168.1.100
  - 192.168.1.200:9301
index: '%{topic}-%{+YYYY.MM.dd}'

这样可以吗

**Comment by childe** [comment]
目前还不行, 数据中没有把topic名字带出来, 我后面加个这个功能吧

**Comment by childe** [comment]
```
- NewKafka:
    topic:
        nginx: 1
    type: nginx
    codec: json
    consumer_settings:
        bootstrap.servers: 192.168.0.1:9092
        value.deserializer: org.apache.kafka.common.serialization.StringDeserializer
        key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
        group.id: hangout

- NewKafka:
    topic:
        tomcat: 1
    codec: json
    type: tomcat
    consumer_settings:
        bootstrap.servers: 192.168.0.1:9092
        value.deserializer: org.apache.kafka.common.serialization.StringDeserializer
        key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
        group.id: hangout

- Elasticsearch:
cluster: prod
hosts:
  - 192.168.1.100
  - 192.168.1.200:9301
index: '%{type}-%{+YYYY.MM.dd}'
```

看了一下, 代码不是很好改, 嘿嘿. 不过上面这样写, 效果是一样的.  额外多说点, group.id建议不要一样.
