### ISSUE TITLE
elasticsearch6    6.3.0 使用search guard

### ISSUE THREAD

**Issue by k8svip** [childe/hangout#134]
WARN  org.elasticsearch.action.bulk.BulkRequestHandler - Failed to execute bulk request 1.
org.elasticsearch.client.transport.NoNodeAvailableException: None of the configured nodes are available:

**Comment by childe** [comment]
使用了SG之后, transport 端口的通讯都是ssl加密的, 我还不知道在hangout里面怎么走transport写数据. 试试HTTP?

```
   - ElasticsearchHTTP:
        cluster: accesslayer_log
        hosts:
          - 192.168.145.128
        index: 'webaccess-%{+YYYY-MM-dd}'
        user: admin
        password: 123456
        index_type: accesslayer
        bulk_actions: 20000
        bulk_size: 15
        flush_interval: 15
```
