### ISSUE TITLE
怎么把日志的时间替换成es中的@timestamp

### ISSUE THREAD

**Issue by niuliwei1029** [childe/hangout#136]
尝试配置了几次没有效果。请问支持这个配置吗？

**Comment by childe** [comment]
```
- Date:
    src: logtime
    formats:
        - 'ISO8601'
    remove_fields: ['logtime']
```

类似这样的

**Comment by niuliwei1029** [comment]
`filters:
    - Filters:
        if:
          - '<#if type??>true</#if>'
          - '<#if type?contains("java_access")>true</#if>'
        filters:
            - Grok:
                match:
                  - '\[%{TIMESTAMP_ISO8601:logtime}\]\^\^A%{GREEDYDATA:msg}'
    - Date:
        src: logtime
        formats:
            - 'ISO8601'
        remove_fields: ['logtime']`
这样配置有问题么？没有生效，报错datafail

**Comment by niuliwei1029** [comment]
```
filters:
    - Filters:
        if:
          - '<#if type??>true</#if>'
          - '<#if type?contains("java-access")>true</#if>'
        filters:
            - Grok:
                match:
                  - '\[%{TIMESTAMP_ISO8601:logtime}\] %{GREEDYDATA:msg}'
    - Date:
        src: logtime
        formats:
            - 'ISO8601'
        remove_fields: ['logtime']
```
这样配置有问题么？没有生效，报错datefail

**Comment by childe** [comment]
输出到stdout, 把日志内容发出来看一下吧. 看报错应该是你的Logtime不是ISO8601格式, 有点奇怪.

你的配置这样写也可以, 但下面这样更简洁一些 

```
filters:
    - Grok:
        if:
          - '<#if type??>true</#if>'
          - '<#if type?contains("java-access")>true</#if>'
        match:
          - '\[%{TIMESTAMP_ISO8601:logtime}\] %{GREEDYDATA:msg}'
    - Date:
        src: logtime
        formats:
            - 'ISO8601'
        remove_fields: ['logtime']
```

**Comment by niuliwei1029** [comment]
```
filters:
    - Filters:
        if:
          - '<#if type??>true</#if>'
          - '<#if type?contains("java_access")>true</#if>'
        filters:
            - Grok:
                match:
                  - '\[%{TIMESTAMP_ISO8601:logtime}\]\^\^A%{GREEDYDATA:msg}'
            - Date:
                src: logtime
                formats:
                    - 'ISO8601'
                remove_fields: ['logtime']
```
这样配置有问题么？logtime 类似2018-10-16 10:41:51,263 ，但没有生效，报错datefail
