### ISSUE TITLE
是否支持output if elasticsearch

### ISSUE THREAD

**Issue by niuliwei1029** [childe/hangout#141]
是否支持类似以下配置？包含if条件的插入到ES数据，不满足则默认规则
```
    - Elasticsearch:
      if:
        - '<#if type?contains("test-access")>true</#if>'
      cluster: es-cluster-test 
      hosts:
        - 192.168.17.183:9200
      index: 'logstash-%{type}-%{+YYYY.MM.dd}'
      index_type: doc
      bulk_actions: 20000
      bulk_size: 15
      flush_interval: 10
      concurrent_requests: 0
      timezone: "Asia/Shanghai"
      sniff: false
```
