### ISSUE TITLE
数据无法写到elasticsearch

### ISSUE THREAD

**Issue by cutd** [childe/hangout#27]
hosts配置的是127.0.0.1:9200
报错说节点不可用。试了很多端口和地址都不行。
我都是用的5.0版本的elasticsearch。克隆也是克隆的5.x分支。
是什么问题啊？

**Comment by cutd** [comment]
```
2016-11-30 10:20:59,592 ERROR com.ctrip.ops.sysdev.outputs.Elasticsearch$1 pool-1-thread-2 None of the configured nodes are available: [{#transport#-1}{3L73i4HYTHCy6auPakWtZg}{127.0.0.1}{127.0.0.1:9200}]
2016-11-30 10:20:59,632 ERROR com.ctrip.ops.sysdev.outputs.Elasticsearch$1 pool-1-thread-3 bulk got exception
2016-11-30 10:22:30,320 ERROR com.ctrip.ops.sysdev.outputs.Elasticsearch$1 pool-1-thread-3 None of the configured nodes were available: [{1JqOY6r}{1JqOY6r0Q1qrs665pY9R9w}{qkFVpIJVQBW0KELmnyZ6NQ}{127.0.0.1}{127.0.0.1:9300}]
2016-11-30 10:22:31,859 ERROR com.ctrip.ops.sysdev.outputs.Elasticsearch$1 pool-1-thread-2 bulk got exception

```

**Comment by childe** [comment]
9300端口.
另外, hangout和ES跑在同一台机器? 为什么用的是127?

**Comment by cutd** [comment]
是hangout和es不能在同一台机器吗？
目前elk都在同一台机器上。

**Comment by childe** [comment]
@cutd  可以在一台机器上.  用9300端口, 走的不是HTTP协议.

**Comment by cutd** [comment]
在一台机器上，是不是es的network.host不能绑定在127.0.0.1上？那么应该用哪个地址呢？

**Comment by childe** [comment]
一般都不会把9300绑定在127, 否则怎么建集群?

**Comment by cutd** [comment]
可以麻烦你告诉我一个比较好的解决方法吗？(我现在都在同一台机器上跑着)
比如es配置文件中network.host绑定到192.168.0.26，然后在配置文件中的hosts写上192.168.0.26。
因为是搞了两天也没有把数据写到es中。

**Comment by cutd** [comment]
```
[2016-11-30 17:38:38,781][INFO ][transport                ] [1JqOY6r] publish_address {10.26.69.103:9300}, bound_addresses {0.0.0.0:9300}
[2016-11-30 17:39:09,032][INFO ][http                     ] [1JqOY6r] publish_address {10.26.69.103:9200}, bound_addresses {0.0.0.0:9200}
```

```
2016-11-30 17:40:48,555 ERROR com.ctrip.ops.sysdev.outputs.Elasticsearch$1 pool-1-thread-1 bulk got exception
2016-11-30 17:40:48,555 ERROR com.ctrip.ops.sysdev.outputs.Elasticsearch$1 pool-1-thread-1 None of the configured nodes were available: [{1JqOY6r}{1JqOY6r0Q1qrs665pY9R9w}{qaxfPH4GTESONs4iG26lyQ}{10.26.69.103}{10.26.69.103:9300}]

```
虽然hangout找到了publish_host但是还是会报错节点不可用。

**Comment by childe** [comment]
clustername配置对吗? 把你的配置发我看一下.

**Comment by cutd** [comment]
```
outputs:
    - Elasticsearch:
        cluster: hangoutcluster

cluster.name: hangoutcluster
```

**Comment by cutd** [comment]
```
[2016-12-01 17:48:01,467][INFO ][transport                ] [hangout-test] publish_address {10.44.21.155:9300}, bound_addresses {10.44.21.155:9300}
[2016-12-01 17:48:04,638][INFO ][http                     ] [hangout-test] publish_address {10.44.21.155:9200}, bound_addresses {10.44.21.155:9200}

2016-12-01 17:48:51,857 ERROR com.ctrip.ops.sysdev.outputs.Elasticsearch$1 Thread-4 None of the configured nodes were available: [{hangout-test}{97oKuNsZSGaVfjVH4wQOXQ}{yfgRHzzmTA2Q1xphNNeOSw}{10.44.21.155}{10.44.21.155:9200}]

```
我现在比较怀疑是不是不支持阿里云服务器啊。因为我换成两台机器依然不可以

**Comment by childe** [comment]
这个不太可能, 怀疑是是版本不一致吧. 你直接下载 https://github.com/childe/hangout/releases/tag/5.0.0 这里的呢

**Comment by cutd** [comment]
我在编译5.0.0发现不能运行之后就直接下载了你打包好的。但是仍然无法连接。端口和host都可用。集群的名字也完全是一致。我看了你的源码和es官方文档也基本一致。实在想不出问题出在哪里。

**Comment by childe** [comment]
报错里面的hangout-test是什么东西?? 你把集群名字配置成这个了??

**Comment by cutd** [comment]
hangout-test 是因为我在一台名为test的服务器上开了一个es，并把集群名和节点名都设置成了hangout-test。kibana和logstash都能正常访问es。就唯独hangout不行。`[2016-12-01 17:48:01,467][INFO ][transport                ] [hangout-test] publish_address {10.44.21.155:9300}, bound_addresses {10.44.21.155:9300}
`这条log也显示9300端口是开启了的。hangout-test是节点名称。但是怎样都会报错节点都不可用。

**Comment by childe** [comment]
集群名字叫hangout-test, 为啥配置里面写的是hangoutcluster ? 
两边配置需要一样

**Comment by cutd** [comment]
两个配置的名字肯定是一致的。。。hangout-test和hangoutcluster是不同的两次测试用的名字。

**Comment by cutd** [comment]
你能告诉我一下你在一台机器测试hangout写数据到es是使用什么样的配置吗。es和hangout的。谢谢了·

**Comment by childe** [comment]
ES:
network.host: 10.1.1.100

hangout:
  
  - Elasticsearch:
        cluster: XXXX
        hosts:
          - 10.1.1.100

hosts那里端口要么不写(默认用会9300), 要么写明是9300, 不要用9200.  我看你有次BULK失败的报错是写的9200.

如果还有问题, 把你完整的配置, 以及ES启动的日志, 以及报错的日志发出来看一下吧.

**Comment by cutd** [comment]
### hangout的log输出
2016-12-06 15:08:22,024 ERROR com.ctrip.ops.sysdev.outputs.Elasticsearch$1 elasticsearch[_client_][bulk_processor][T#1] bulk got exception
2016-12-06 15:08:22,026 ERROR com.ctrip.ops.sysdev.outputs.Elasticsearch$1 elasticsearch[_client_][bulk_processor][T#1] None of the configured nodes were available: [{hangout-test}{97oKuNsZSGaVfjVH4wQOXQ}{phQqeD4kTReVb2UfJFITkA}{10.44.21.155}{10.44.21.155:9300}]
### es的log输出
[2016-12-06 15:07:34,212][INFO ][transport                ] [hangout-test] publish_address {10.44.21.155:9300}, bound_addresses {10.44.21.155:9300}

## 这是hangout的配置文件

```
inputs:
    - NewKafka:
        topic:
            online: 3
        codec: json
        consumer_settings:
            bootstrap.servers: kafka-00.vbyte.io:9092,kafka-01.vbyte.io:9092,kafka-02.vbyte.io:9092
            value.deserializer: org.apache.kafka.common.serialization.StringDeserializer
            key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
            group.id: hangout

filters:
    - Date:
        src: TIMESTAMP
        formats:
            - 'ISO8601'
            - 'UNIX'
        remove_fields: ['logtime']
        fields: ['timestamp']
    - Remove:
        fields:
          - message
    - Json:
        field: message # required
    - GeoIP2:
        source: IP # required
        target: geoip # default geoip
        database: '/tmp/GeoLite2-City.mmdb'
        country_code: false # default true
        country_name: false # default true
        country_isocode: false # default true
        subdivision_name: true # default true
        city_name: true # default true
        latitude: false # default true
        longitude: false # default true
        location: false # default true

outputs:
    - Elasticsearch:
        cluster: hangout-test 
        hosts:
            - 10.44.21.155:9300
        index: 'hangout-%{+YYYY.MM.dd}'
        index_type: logs # default logs
        #document_id: ${id} # defautt null, generated by es
        bulk_actions: 20000 #default 20000
        bulk_size: 15 # default 15 MB
        flush_interval: 10 # default 10 seconds
        concurrent_requests: 0 # default 0, concurrent_requests设置成大于0的数, 意思着多线程处理, 以我应用的经验,还有是一定OOM风险的,强烈建议设置为0
        timezone: "Asia/Shanghai" # defaut UTC 时区. 只用于生成索引名字的字符串格式化
        sniff: false #default true
```

## 这是ES的配置文件
```
# ======================== Elasticsearch Configuration =========================
#
# NOTE: Elasticsearch comes with reasonable defaults for most settings.
#       Before you set out to tweak and tune the configuration, make sure you
#       understand what are you trying to accomplish and the consequences.
#
# The primary way of configuring a node is via this file. This template lists
# the most important settings you may want to configure for a production cluster.
#
# Please see the documentation for further information on configuration options:
# <http://www.elastic.co/guide/en/elasticsearch/reference/current/setup-configuration.html>
#
# ---------------------------------- Cluster -----------------------------------
#
# Use a descriptive name for your cluster:
#
cluster.name: hangout-test
#
# ------------------------------------ Node ------------------------------------
#
# Use a descriptive name for the node:
#
node.name: hangout-test
#
# Add custom attributes to the node:
#
node.data: true
# node.rack: r1
#
# ----------------------------------- Paths ------------------------------------
#
# Path to directory where to store the data (separate multiple locations by comma):
#
path.data: /data/es/data
#path.data: /var/lib/es
#
# Path to log files:
#
path.logs: /data/es/logs
#path.logs: /var/lib/es
#
# ----------------------------------- Memory -----------------------------------
#
# Lock the memory on startup:
#
# bootstrap.memory_lock: true
#
# Make sure that the heap size is set to about half the memory available
# on the system and that the owner of the process is allowed to use this
# limit.
#
# Elasticsearch performs poorly when the system is swapping the memory.
#
# ---------------------------------- Network -----------------------------------
#
# Set the bind address to a specific IP (IPv4 or IPv6):
#
network.host: 10.44.21.155
network.publish_host: 10.44.21.155
#
# Set a custom port for HTTP:
#
#http.port: 9200
transport.tcp.port: 9300
#
# For more information, see the documentation at:
# <http://www.elastic.co/guide/en/elasticsearch/reference/current/modules-network.html>
#
# --------------------------------- Discovery ----------------------------------
#
# Pass an initial list of hosts to perform discovery when new node is started:
# The default list of hosts is ["127.0.0.1", "[::1]"]
#
discovery.zen.ping.unicast.hosts: ["10.44.21.155"]
#
# Prevent the "split brain" by configuring the majority of nodes (total number of nodes / 2 + 1):
#
discovery.zen.minimum_master_nodes: 1
#
# For more information, see the documentation at:
# <http://www.elastic.co/guide/en/elasticsearch/reference/current/modules-discovery.html>
#
# ---------------------------------- Gateway -----------------------------------
#
# Block initial recovery after a full cluster restart until N nodes are started:
#
# gateway.recover_after_nodes: 3
#
# For more information, see the documentation at:
# <http://www.elastic.co/guide/en/elasticsearch/reference/current/modules-gateway.html>
#
# ---------------------------------- Various -----------------------------------
#
# Disable starting multiple nodes on a single system:
#
node.max_local_storage_nodes: 1
#
# Require explicit names when deleting indices:
#
# action.destructive_requires_name: true

```
