### ISSUE TITLE
消费Kafka线程数问题

### ISSUE THREAD

**Issue by binmu123** [childe/hangout#60]
你好 我用一个hangout来消费kafka中多个topic的数量
每个topic的partition都是十
大约消费10个topic的数据吧，然后写入es，我的配置中有两个是设置线程数的
        topic:
          app_fix: 2
        consumer_settings:
          num.consumer.fetchers: "3"
第一个设置：开2个线程取app这个topic的数据
第二个设置：启动Consumer的个数，适当增加可以提高并发度
但是报错
java.lang.IllegalStateException: bulk process already closed
	at org.elasticsearch.action.bulk.BulkProcessor.ensureOpen(BulkProcessor.java:281)
	at org.elasticsearch.action.bulk.BulkProcessor.internalAdd(BulkProcessor.java:286)
	at org.elasticsearch.action.bulk.BulkProcessor.add(BulkProcessor.java:271)
	at org.elasticsearch.action.bulk.BulkProcessor.add(BulkProcessor.java:267)
	at org.elasticsearch.action.bulk.BulkProcessor.add(BulkProcessor.java:253)
	at com.ctrip.ops.sysdev.outputs.Elasticsearch.emit(Elasticsearch.java:226)
	at com.ctrip.ops.sysdev.outputs.BaseOutput.process(BaseOutput.java:60)
	at com.ctrip.ops.sysdev.inputs.Kafka$Consumer.run(Kafka.java:77)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
2017-02-17 18:43:24,758 ERROR com.ctrip.ops.sysdev.inputs.Kafka$Consumer pool-31-thread-1 java.lang.IllegalStateException: bulk process already closed
想请问一下这个跟我设置的线程数的问题有关？还是es问题？还有那两个参数具体该怎么理解？
谢谢！

**Comment by gnuhpc** [comment]
能贴一下你hangout es的配置吗，另外这个错误是一启动就有还是在关闭的时候发生的？

**Comment by binmu123** [comment]
es的配置如下
outputs:
   - Elasticsearch:
        cluster: es5000
        hosts:
           - ip
        index: 'feed-%{+YYYY.MM.dd}'
        index_type: logs # default logs
        bulk_actions: 20000 #default 20000
        bulk_size: 15 # default 15 MB
        flush_interval: 10 # default 10 seconds
        concurrent_requests: 0 
        timezone: "Asia/Shanghai" #
        sniff: false
这个错误是启动一会之后报的错。我怀疑是我读的kafka的多个topic开的线程总量过多。不知道对不对？希望讲解一下。

**Comment by gnuhpc** [comment]
在这个报错发生的时候es那边的日志和集群状态是否有异常？单看这些信息感觉是后边的es扛不住了，不过我不是很确定。

**Comment by childe** [comment]
@binmu123 家里宽带断了, 回晚了. 我觉得很可能是线程数太多了.
10topic, 每个2线程, 就20线程, 只算最后ES client需要的内存, 10*2*15M =  300M, request发送时还需要复制一份, 再加上response, 实际内存还要乘2.X ~= 600M. 600M数据在heap中可能还要再乘个系数, 会接近2G, 这还没算kafka input占用. hangout默认中分配最多2Gheap, 所以我觉得很可能会OOM.
要么把消费的topic分配到不同进程中去, 要么把hangout heap增大一些.
export HO_HEAP_SIZE=8G

**Comment by binmu123** [comment]
@gnuhpc 
当时写入的时候，我这边报错，查了es，es没有异常。
而且我虽然读了多个topic但是这些topic数据量大小不一样。
但是topic在设计的时候，每个topic都是十个partition。但是数据量不一，有的一天10G左右有的一天才几M，我所有读取kafka都开启3个线程，3个fetchers。
会不会跟这个有关系？

**Comment by binmu123** [comment]
@childe 
非常感谢回答。
恩，我也感觉是线程数太多，我把消费topic分配到不同的进程去了，解决了这个问题。谢谢了

**Comment by jwcn** [comment]
您好, 我也遇到这个错误, 方便帮看下吗? 我设置两个 topic , 每个 topic 配置 8 个线程消费, heap_size 设置的10g

```
inputs:
    - Kafka:
        codec: plain
        encoding: UTF8 # defaut UTF8
        topic:
            lion-log: 8
            lion_request-log: 8
        consumer_settings:
            group.id: hangout_lion
            zookeeper.connect: 10.19.176.68:2181
            auto.commit.interval.ms: "1000"
            auto.offset.reset: "smallest"
filters:
    - Json:
        field: message # required
        tag_on_failure: '' # do not add tags; deafult "jsonfail"
outputs:
    - Elasticsearch:
        cluster: elasticsearch
        hosts:
          - 10.19.22.142
        index: '%{@index}'
        index_type: '%{@type}' # default logs
        #document_id: ${id} # defautt null, generated by es
        bulk_actions: 20000 #default 20000
        bulk_size: 15 # default 15 MB
        flush_interval: 10 # default 10 seconds
        concurrent_requests: 0 # default 0, concurrent_requests设置成大于0的数, 意思着多线程处理, 以我应用的经验,还有是一定OOM风险的,强烈建议设置为0
        #timezone: "Asia/Shanghai" # defaut UTC 时区. 只用于生成索引名字的字符串格式化
        sniff: true #default true
```
