### ISSUE TITLE
Error: Could not find or load main class com.ctrip.ops.sysdev.Main

### ISSUE THREAD

**Issue by jwcn** [childe/hangout#68]
执行 bin/hangout -f lion.yml 
报错
Error: Could not find or load main class com.ctrip.ops.sysdev.Main

请教下我是哪里没配置好吗

**Comment by childe** [comment]
你是自己编译的, 还是下载的release里面的?

**Comment by jwcn** [comment]
我是直接 clone 后, checkout 到 es2.x 的, 没有编译

**Comment by jwcn** [comment]
恩应该是我安装方式不对,我下载release试一下,打扰了

**Comment by jwcn** [comment]
我下载的release版本0.2.1, 运行报错, 麻烦帮忙看一哈,谢谢
`
jw@dev:/opt/hangout$ sudo bin/hangout -f lion.yml 
Hangout  Version:0.2.1  Copyright @Ctrip   Author : childe@github, gnuhpc@github
while scanning a simple key
 in 'reader', line 30, column 1:
    ~
    ^
could not find expected ':'
 in 'reader', line 31, column 1:
    
    ^

        at org.yaml.snakeyaml.scanner.ScannerImpl.stalePossibleSimpleKeys(ScannerImpl.java:465)
        at org.yaml.snakeyaml.scanner.ScannerImpl.needMoreTokens(ScannerImpl.java:280)
        at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:225)
        at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:557)
        at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:157)
        at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:147)
        at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:224)
        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:155)
        at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:246)
        at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:237)
        at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:225)
        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:155)
        at org.yaml.snakeyaml.composer.Composer.composeSequenceNode(Composer.java:199)
        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:153)
        at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:246)
        at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:237)
        at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:225)
        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:155)
        at org.yaml.snakeyaml.composer.Composer.composeDocument(Composer.java:122)
        at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:105)
        at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:120)
        at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:450)
        at org.yaml.snakeyaml.Yaml.load(Yaml.java:381)
        at com.ctrip.ops.sysdev.config.HangoutConfig.parse(HangoutConfig.java:35)
        at com.ctrip.ops.sysdev.core.Main.main(Main.java:41)
`

**Comment by jwcn** [comment]
我的配置
```
inputs:
    - Kafka:
        codec: plain
        encoding: UTF8 # defaut UTF8
        topic:
            test2: 16
            #lion_request-log: 16
        consumer_settings:
            group.id: hangout
            zookeeper.connect: 192.168.12.29:2181
            auto.commit.interval.ms: "1000"
filters:
    - Json:
        field: message # required
        tag_on_failure: '' # do not add tags; deafult "jsonfail"
outputs:
    - Elasticsearch:
        cluster: elasticsearch
        hosts:
          - 192.168.12.29
        index: '%{index}'
        index_type: '%{type}' # default logs
        #document_id: ${id} # defautt null, generated by es
        bulk_actions: 20000 #default 20000
        bulk_size: 15 # default 15 MB
        flush_interval: 10 # default 10 seconds
        concurrent_requests: 0 # default 0, concurrent_requests设置成大于0的数, 意思着多线程处理, 以我应用的经验,还有是一定OOM风险的,强烈建议设置为0
        #timezone: "Asia/Shanghai" # defaut UTC 时区. 只用于生成索引名字的字符串格式化
        sniff: false #default true
~
```
