### ISSUE TITLE
希望elasticsearch OUTPUT插件中增加username和password配置项

### ISSUE THREAD

**Issue by charmfocus** [childe/hangout#71]
在安装了x-pack后，需要带上用户和密码，elasticsearch OUTPUT插件不能配置

**Comment by childe** [comment]
是指的HTTP接口的吗?

**Comment by childe** [comment]
后续会加上transport和http两种client的.

**Comment by childe** [comment]
transport的.

因为x-pack使用了新的类(https://www.elastic.co/guide/en/x-pack/5.3/java-clients.html), 所以我单独写了下, 见附件. 

1. 把它放在hangout的modules文件夹下, 删除之前modules下面的elasticsearch-X.X.X.jar
2. 下载 https://artifacts.elastic.co/maven/org/elasticsearch/client/x-pack-transport/5.3.2/x-pack-transport-5.3.2.jar 放在hangout的libs文件夹下
3. 配置如下

```
outputs:
    - Elasticsearch:
        cluster: elasticsearch
        hosts:
          - 10.1.1.100
        index: 'test'
        index_type: "logs"
        bulk_actions: 5000
        bulk_size: 20
        flush_interval: 30
        concurrent_requests: 0
        compress: true
        sniff: false
        settings:
            xpack.security.user:transport_client_user:changeme
```

[hangout-output-es5-xpack-0.1.jar.zip](https://github.com/childe/hangout/files/1001052/hangout-output-es5-xpack-0.1.jar.zip)
