### ISSUE TITLE
Elasticsearch output 如何获取日志中的时间

### ISSUE THREAD

**Issue by RickyHuo** [childe/hangout#75]
Hangout  Version:0.2.1

我希望根据日志里的时间设定index。但是我根据首页README.md配置出现报错

```
- Elasticsearch
    cluster: es
    host:
        - 127.0.0.1
    index: 'hangout-${@timestamp.toString("YYYY.MM.dd")}'
    index_type: logs
    bulk_actions: 20000
    bulk_size: 15
    flush_interval: 10
    concurrent_requests: 0
```

报错信息如下：
> ERROR com.ctrip.ops.sysdev.outputs.Elasticsearch$1 elasticsearch[_client_][bulk_processor][T#1] RemoteTransportException[[127.0.0.1][127.0.0.1:9300][indices:admin/create]]; nested: InvalidIndexNameException[Invalid index name [hangout-${@timestamp.toString("YYYY.MM.dd")}], must not contain the following characters [ , ", *, \, <, |, ,, >, /, ?]];
