### ISSUE TITLE
message Gsub不好使，这种数据该怎么用hangout处理呢？

### ISSUE THREAD

**Issue by mrzhangxing** [childe/hangout#88]
源数据

> {
"@timestamp":"2017-08-03T10:14:22+08:00",
"@fields":{"cluster":"detail_pool","request":"GET","body_bytes_sent":"9273","http_uid":"26","upstream_status":"200","protocol":"http","hostname":"localhost"}
}

最终只想要

>  {
"@timestamp":"2017-08-03T10:14:22+08:00",
"cluster":"detail_pool",
"upstream_status":"200"
}

logstash可以处理，但是hangout不知道用什么语法，我想用先将@fields替换字典，然后在grok，发现替换失败
- Gsub:
    fields:
        'message': ['"@fields"','{"@fields"}']

又麻烦了哈~

**Comment by childe** [comment]
```
filters:
    - Add:
          fields:
              cluster: '[@fields][cluster]'
              upstream_status: '[@fields][upstream_status]'
```
