### ISSUE TITLE
Date filter解析YYYYMMddHHmmss的问题

### ISSUE THREAD

**Issue by modeyang** [childe/hangout#96]
如题， 如果时间格式是YYYYMMddHHmmss这种，利用hangout解析出来的utc时间有点问题。

如果字段d='20170913111057', 利用date filter默认timezone和local
```
    - Date:
        src: d
        formats:
            - 'YYYYMMddHHmmss'
```
解析出来的@timestamp为**2017-09-13T11:10:57.000+08:00**， 如果加上timezone为Asia/Shanghai, 保持不变， 如果timezone为UTC, 值变成2017-09-13T11:10:57.000Z; 这样在kibana默认配置下时间后移了8个小时

并且如果在logstash用这样的时间格式做filter的话， 是正确的， ```"@timestamp" => "2017-09-13T11:02:57.000Z"```

但是我想要的是**2017-09-13T11:02:57.000Z**， 请问怎么破啊？ @childe

**Comment by modeyang** [comment]
刚刚测试了下， joda代码
```
       String input = "20170913103120";
        DateTimeFormatter p = FormatParser("YYYYMMddHHmmss", "Asia/Shanghai", null);
        System.out.println(p.parseDateTime(input));

        DateTime d = new DateTime(p.parseMillis(input));
        System.out.println(d);

        Instant instant = new Instant(p.parseMillis(input));
        System.out.println(instant);
返回结果
2017-09-13T10:31:20.000+08:00
2017-09-13T10:31:20.000+08:00
2017-09-13T02:31:20.000Z
```
感觉默认的DateTime加了timezone之后就不太对了， 如果返回Instant，结果就是对的。 我看了下logstash date filter,  通过parser函数返回的值是Instant而非DateTime类型， 感觉需要改下。
可以加你QQ话， 有什么问题可以直接沟通。

**Comment by childe** [comment]
我看起来都是"正确的逻辑", 包括你的测试代码. hangout里面默认timezone是local, 不是UTC. 你的YYYYMMddHHmmss是什么时区就配置什么时区, 我建议显式的写明是"Shanghai"或者是UTC.
2017-09-13T11:10:57.000+08:00和2017-09-13T11:10:57.000Z 两个是一样的, Z是代表0时区.

**Comment by childe** [comment]
64973150 但我还是希望能在这上面把事情说清楚, 至少把结论写下来.

**Comment by modeyang** [comment]
我上面说了即使我加了timezone字段，格式转换后的时间戳也不是我设想的。
```
  - Date:
        src: d
        timezone: Asia/Shanghai
        formats:
            - 'YYYYMMddHHmmss'
```
结果： ```@timestamp=2017-09-14T10:07:46.000+08:00,  d=20170914100746```,  所以我才有了下面的测试，看了Logstash Date filter的代码发现那边返回的是Instant类型的时间，根据我的测试是可以的。

你真名叫？
