### ISSUE TITLE
datefail:  2017 Sep 30 10:40:00

### ISSUE THREAD

**Issue by mrzhangxing** [childe/hangout#98]
date的文本是'2017 Sep 30 10:40:00'

 - Date:
        src: date
        formats:
            - 'YYYY hh dd HH:mm:ss'
            - 'YYYY MMM dd HH:mm:ss''

请问的日志如何转换呢，以上写法报datefail，在logstash中【- 'YYYY MMM dd HH:mm:ss''】这个是ok的

**Comment by childe** [comment]
```
 - Date:
        src: date
        locale: en
        formats:
            - 'YYYY MMM dd HH:mm:ss''
```
