### ISSUE TITLE
配置文件能否增加include指令，类似于ansible playbook的include指令一样

### ISSUE THREAD

**Issue by modeyang** [childe/hangout#99]
如题，这样的话，可以在日志格式大体相同的日志中尽可能复用配置；
同时可以在input增加类logstash的input的type字段作为服务区分；

**Comment by childe** [comment]
关于include, 今天看了一下, yaml本身不支持这样的语法, java库, 至少我用的snake这个库也不支持这样的语法. ansible里面如何实现的我还没看, 不过我不是很想自己去"增强"yaml的语法(主要是没能力)
但是可以用yaml的merge语法组合实现这样的类似的功能.

```
Template:
    - &kafka
        codec: json
        topic: {}
        consumer_settings:
            group.id: hanogut.web
            zookeeper.connect: "10.10.10.100:2181"
            auto.commit.interval.ms: "1000"
    - &elasticsearch
        cluster: clustername
        hosts: []
        index: ''
        index_type: "logs"
        bulk_actions: 20000
        bulk_size: 20
        flush_interval: 60
        concurrent_requests: 0
        sniff: false
        compress: true
        settings:
            processors : 1
inputs:
    - Kafka:
        <<: *kafka
        topic:
            web: 1
            app: 1

filters:
    - Grok:
        src: message
        match:
            - '^\[%{HTTPDATE:logtime}\]"'
    - Date:
        timezone: 'Asia/Shanghai'
        src: logtime
        formats:
            - 'dd/MMM/YYYY:HH:mm:ss Z'
        remove_fields: ["logtime"]

outputs:
    - Elasticsearch:
        <<: *elasticsearch
        hosts:
            - 10.10.10.200
        index: 'web-%{+YYYY.MM.dd}'
```
上面的Template放在一个base.yml里面, 下面的inputs outputs等放在web.yml里, 然后 `cp base.yml my.yml; cat web.yml >> my.yml ; bin/hanout XXX`
